### PR TITLE
Jb 3.0

### PR DESCRIPTION
**Pull request by doadin**
Some indludes may need to be updated too like this one:
https://github.com/doadin/samsung-kernel-msm7x30/commit/324ad7ff006003d178e7c019c197ced43210fdce

### CODE REVIEW

**Comment by arco** [comment]
It's working ok for you on ancora_tmo?

I need to test that the include changes doesn't break anything regarding ancora battery.

**Comment by doadin** [comment]
Not exactly sure yet. Going to test a bit make sure it wont break anything.

**Comment by doadin** [comment]
For some reason after these changes i get com.android.phone fc's i wiped the chache/delvik but it still happends.
logcat:http://pastebin.com/dd90Wz6e

The battery driver seems to work phone runs on battery and still detects usb(id assume other connections too) but i cant really test more because of the fc's.(cant open setting app to see what it says for connection)

I thinnk it has something to do with the change in battery_status

**Comment by arco** [comment]
That's odd. It shouldn't cause any fc's afaik.

**Comment by doadin** [comment]
Yea idk, but i made 2 build one with debug and one without in the battery driver. Both caused FC's. I tried flashing each 2 times. And in between flashing back to regular kernel from your sources reg works fine,with these changes fc's. The only thing i could think of is the change in status. I saw a commit on the cyanogenmod gerrit for battery drivers that report improper statuses or something like that but i dont know if thats what this does or where that commit even is. Its the only thing i can think of that changes that could possibly have any effect.

**Comment by doadin** [comment]
did not mean to add that last one.

**Comment by doadin** [comment]
Closeing because the battery seems to work fine now with the changes made in cm10.1 branch. If you wana maybe copy them over to CM10_3.0. Also question though, was the odd battery % the reason you reverted the 3.0 kernel power management commit?

**Comment by arco** [comment]
Point me to the revert, as I don't remember.

**Comment by doadin** [comment]
Never mind i was looking at https://github.com/arco/samsung-kernel-msm7x30/commit/33e2c44807e4fadb968333ad8becbc6ebe711cd6 to https://github.com/arco/samsung-kernel-msm7x30/commit/9063bb06f5da656a824b1f87383754d3e1f4baf1 but its not really a revert just a few things moved back.

**Pull request closed without merging**
