### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by sirmordred**
with CMA patch ram is 426 mb now
ı have been using/testing CMA patch for one week and so far so good..
and using lz4 for zram is giving little nice increase on overall performance

### CODE REVIEW

**Comment by Christopher83** [comment]
Hi Oğuzhan,
I'll test them too...
About ION heaps change, are camera & camcorder, hw video playback working fine?

Thanks a lot.

**Comment by sirmordred** [comment]
Thank you Chris
yes ı've been using ION heap change for one week and everything is working(camera,camcorder and hw/sw playback)
only 720p isnt working but ı guess its not related ION heap change because before this change it was already not working(it can be app or upstream CM issue)

regards

**Comment by Christopher83** [comment]
Perfect, thanks!

**Comment by Christopher83** [comment]
Is deep sleep working for you?
I think it's aways the same problem, already fixed in the past, but I'd like to know if you're experiencing that too...
Let me know.

**Comment by sirmordred** [comment]
yeah you are right Chris
deep sleep isnt working for me too
also what ı saw in latest build is
mediaprovider is consuming battery more than screen (probably its related to CM's new theme engine)
ı will also send screenshot for about this

**Comment by Christopher83** [comment]
This commit solves deep sleep issue:
https://github.com/AriesVE-DevCon-TEAM/samsung-kernel-msm7x30/commit/b228f3f776faadb1e0a9dbc450b0cd43843c11e4

**Comment by sirmordred** [comment]
Chris can you also try this change? https://github.com/sirmordred/samsung-kernel-msm7x30/commit/869a635e3d5339fb2886ce7e1b4fd3320e569600
maybe a better fix

regards

**Comment by sirmordred** [comment]
added inline comments

**Comment by sirmordred** [comment]
ok ı rebased the pull request
remaining changes are tested by me and its good to go

**Comment by arco** [comment]
If there's anything else that should be merged, push again cleanly without all the old stuff, and only if it's tested AND working.

**Pull request closed without merging**
