### PR TITLE
Various kernel updates

### PR DESCRIPTION
**Pull request by sirmordred**

### CODE REVIEW

**Comment by arco** [comment]
About has_outer_cache, I don't know. Samsung does really strange things some times.

**Comment by sirmordred** [comment]
yeah totally agree CastagnaIT other phones(semc mogami and huawei u8800) is using same overlay0 &ion wb even which dont have HDMI support

**Comment by mikeNG** [comment]
We have to use overlay0 writeback in semc & huawei to workaround some qcom mddi bugs. @Blefish knows a lot more about this. Samsung msm7x30 use lcdc so I don't know if it's actually useful for you.

**Comment by rtammekivi** [comment]
In theory, only the older msm7x30 need overlay 0 writeback (like huawei u8800 / semc zeus?). It's due to the fact that MDDI has underrun problems on these devices with DMA_P pipe (nearly 30fps). We are using DMA_S pipe as a workaround, but DMA_P is not the same as DMA_S. DMA_S does not go through overlay mixer directly. This means that when userspace allocates for example, 2 layers, DMA_S cannot show these properly (it does not show one layer properly too because base layer is not for composition in userspace). 

Writeback is a special mode in MDP where the image is composed in overlay mixer (with all the layers) and sent back to the MDP crossbar. From there it's possible to use the DMA_S pipe to show the image on the screen.

The writeback is basically what it says, write back. It's not related to HDMI directly, although it is used by HDMI. I am currently enabling analog TV out on my U8800 and it works without writeback.

**Comment by sirmordred** [comment]
ı will close this and will open new one

**Pull request closed without merging**
