### PR TITLE
cypress-touchkey: attempt to filter out "phantom" key-presses

### PR DESCRIPTION
**Pull request by CastagnaIT**
ariesve is affected by this problem, this workaround is based on:
https://github.com/CyanogenMod/android_kernel_samsung_aries/commit/4afad77c61c7cb54cce293034cdb07a928f22d20

https://github.com/CyanogenMod/android_kernel_samsung_aries/commit/cb8fa22cba177709848321e8100ee60ee1684530

### CODE REVIEW

**Comment by Christopher83** [comment]
Stefano, could you take a look at my commit, this also includes the home key presses filtering :+https://github.com/Christopher83/samsung-kernel-msm7x30/commit/e688f0b32151d8cd61d07377b014371451f8114b1:

**Comment by CastagnaIT** [comment]
arco wait to add this pull request,
I noticed strange problems with the display..
I do not know if it depends on this

Christopher the link is wrong...

**Comment by Christopher83** [comment]
The solution for aries devices is not completely working for our devices, needs adaptations and further changes. 
This link works? 
https://github.com/Christopher83/samsung-kernel-msm7x30/commit/e688f0b32151d8cd61d07377b014371451f8114b

You may also find additional infos on my xda kernel thread

Thanks

**Comment by CastagnaIT** [comment]
ooh thanks i'm already testing

**Pull request closed without merging**
