### PR TITLE
drivers/media/video/msm/ledflash.c: Add Sysfs Entries

### PR DESCRIPTION
**Pull request by doadin**
This will create sysfs entries:
/sys/kernel/testflash/flashon
/sys/kernel/testflash/flashoff
Sill need to work on reading/writing the values. As of now when the flash is on it should set /sys/kernel/testflash/flashon = 1. And when the flash is off /sys/kernel/testflash/flashoff = 1.

### CODE REVIEW

**Comment by arco** [comment]
Torch app can only handle one sysfs node. It should also not turn off LED when screen is off, and not cause any flickering.

**Comment by doadin** [comment]
Are these just some general rules or would that actually happen in its current state? I think i know what you mean and this was kinda a first run i just wanted to establish a sysfs with usefull information toward the task at hand. I was thinking maybe a quick way would be to just make one more entrie and have that one check either on or off was 1 or 0 but still need one to read the value from sysfs so it can be changed in userspace and that would not be the best way to do it.

**Comment by doadin** [comment]
opps i meant entry is /sys/kernel/flash/flashonoff

**Comment by doadin** [comment]
This should be moved anyways eventually to something like /sys/devices/virtual/ledflash/ledflash/ledflash_file but since that is taken somewhere maybe /sys/devices/virtual/msmflash/msmflash/ledflash. IDK. Ideally we want a location common to most devices to make it easy and compatible with current flashlight apps and/or camera apps.

Either way i think this is a start. 

To address what you said earlier I believe how it is now it should only effect the flash and not the screen. And as for flickering not sure but i think we would want to set it to "movie mode" as thats like setting "torch" instead of just on or off in camera app. However not sure how to handle that yet. This is also probably the worst code written ever but at least i tried lol.

**Comment by doadin** [comment]
Idk if you saw the comments from jfbs but theres now http://review.cyanogenmod.org/#/c/29105/ which should be useful so idk if you still want this commit or something like it. Let me know also if you want anything changed.(or if it even works lol)

**Comment by arco** [comment]
Yeah that's the patch I used to have the app working with /dev/ledflash

I've fixed the issues now though, so it's working as it should now. Had to use wakelocks to prevent it from turning off when screen off.

**Pull request closed without merging**
