### PR TITLE
Some changes to fix touchscreen voltage regulator

### PR DESCRIPTION
**Pull request by Christopher83**
Hi Arne,
these commits should fix the voltage issue of touchscreen and probably the battery drain related to our device.

Let me know if you see that something is wrong...

Thank you very much, as always!

### CODE REVIEW

**Comment by arco** [comment]
Looks ok to me.

Does this also apply to 3.0 kernel?

**Comment by Christopher83** [comment]
Yes I really think so,
the problem on 3.4 is caused by the new constraints inside /drivers/regulator/core.c
On 3.0 actually we can set minV = 2600000, maxV = 2600000 range for a driver and then minV = 1800000, maxV = 2600000 for touchscreen without any error/problem, even if what we're doing is not correct.

**Comment by Christopher83** [comment]
I used this simple script to compare the regulator values on 3.0 and 3.4 kernel

#!/system/bin/sh

cd /d/regulator

for path in *; do
    if [ -d $path ]; then
        echo "\n-----------------------------------\n"
        echo "Path ${path}"
        cd $path

```
    if [ -f consumers ]; then
        echo "* Consumers"
        cat consumers
    fi
    if [ -f voltage ]; then
        echo "* Voltage"
        cat voltage
    fi

    cd ..
fi
```

done

**Comment by Christopher83** [comment]
Sorry Arne,
could you remove the last commit "ariesve: Some changes to the touchscreen power-on routine" and cherry pick the amended new one?
https://github.com/Christopher83/samsung-kernel-msm7x30/commit/42da6e15e2f7764f52b16021b2a97fb22874d9e9

If you compare the old commit and the amended one, at the regulators struct declaration
           static struct regulator_bulk_data oliver_tsp_regs[] = { 
I simply changed this line:
           { .supply = "gp4", .min_uV = 1800000, .max_uV = 2600000 }, 
to be
           { .supply = "gp4", .min_uV = 1800000, .max_uV = 1800000 }, 
as the previous used values (with the old code).

This change is ininfluent, since the touchscreen, also with the range 1800000 - 2600000 uses always the min voltage of 1800000 uV, but it's just to keep the same configuration as before...

Thanks again...

**Comment by arco** [comment]
Done.

**Pull request closed without merging**
