### PR TITLE
Fix battery level being off from battery voltage

### PR DESCRIPTION
**Pull request by doadin**

### CODE REVIEW

**Comment by doadin** [comment]
Im not sure this is exactly a "right way of doing it" or if i even did it right but i think we need to change how the voltage level and battery level like "sync" if you will and that will correct the percentage. I think the battery level is used to display the percentage and it reports full when the voltage gets to ~4180? I cant remember if that numbers right. I think the fast charge disrupted the matching of the 2 and until they align it will always be off. So if we are going to use that we should implement a check like above to ensure they stay synced. In other words if we are at ~4180uV then battery level should be 100.(4200 is max capacity) At the very least i hope this commit gives you an idea and you can fix it up to do what it should.

I think this is the case because even after switching back to a rom/zip that was working 100% like it should, as far as battery goes, didn't fix it then it cant be the fault of any of the commits, at least not directly. And we should just add checks to make sure it stays right.

**Comment by doadin** [comment]
It safe to assume since you released a new build that im just crazy and its fine? :P

**Comment by arco** [comment]
I'll test this when I have time. :) I don't think the fast charging has
anything to do with it, cause it's disabled by default and can only be
activated by writing to a sysfs file.

**Comment by doadin** [comment]
Yea, im not sure what caused it because now it seems no matter what i do its still off. Any ideas how i can get it back to normal? Think maybe i have to do wipes?

**Comment by arco** [comment]
No idea, unfortunately. But you might try a wipe yes.

**Comment by doadin** [comment]
OK well thanx anyways. Ill try different things see if i can get it restored.

Wipes didn't help gonna try letting it die then charging it full. Still think: 1. Should fix that one line because it just doesnt make sence. 2. Fix it up in a way that will fix the percentage being off, just because it would overall be better. I think right now its doing the percentage based off time somehow or something. Idk i haven't looked at it much.

**Comment by doadin** [comment]
Im not sure on how to change this commit but i actually think i maybe have found what i was looking for:
I actually found this in drivers / power / msm_battery.c which seems like the two are pretty much the same driver. Looking through the code there are very few differences one of them being the following, which seems like it would handel the bat_capacity better.(Which is probably why they changed it) 

static u32 msm_batt_capacity(u32 current_voltage)
 {
         u32 low_voltage = msm_batt_info.voltage_min_design;
         u32 high_voltage = msm_batt_info.voltage_max_design;

```
     if (current_voltage <= low_voltage)
             return 0;
     else if (current_voltage >= high_voltage)
             return 100;
     else
             return (current_voltage - low_voltage) * 100
                     / (high_voltage - low_voltage);
```

**Comment by doadin** [comment]
Hey, just making another note.(sorry if this spams you email or something) Im fairly positive its not a problem with my actually battery because it does the same with other batteries.(unless all 3 of the batteries i have are bad >.<,just trying to narrow down the issue) They all stop chargeing around the same volts ~4180. However the percent is always read differently any where from 91-98% and eventually after staying pluged in reaching 100%. So something deffinatly seems wrong in the percent calculation if the same voltage equals a different percentage and not just within +/-1%. Sorry if this isnt helpfull just trying to note all that i notice to help.

I think the problem maybe have to do with the fuel_gauge. Seems like with the stock battery driver it incorporates information from that in its calculating %. I think the easiest way to fix this would to be to change over to the msm battery driver that came with the kernel, +/- a few changes as far as getting it to work. 

I think if we at least used the above mentioned code instead of what ever crazy thing is going on now we would at least have something that will give a reliable close number to what it should be instead of something that is +/-10% of where it actually is.

**Comment by doadin** [comment]
Just had a thought, it might be the fuel gauge chip thats the culprit? If i read logs right it seems like it always says the same thing as the percent. And its the only thing i can think of that doesnt get reset between flashes? I saw somewhere hot to reset it but i think its either a different version chip or its not working right? Ill look to see if i can tell how to reset it and if it has any effect.(again just throwing out ideas so you have an idea what might and might not work no rush) Also think i might close this the change is a bad one so no point in keeping this.

**Pull request closed without merging**
