### PR TITLE
Cm 10.1 - Some changes

### PR DESCRIPTION
**Pull request by Christopher83**
Hi Arne,
the first commit updates the "atv_dac_power" routine on "board-ariesve.c" to use the regulators defined on "board-ariesve-regulator.c". This code is already used on cm-10.1_3.0 branch.

The second commit simply rename a wrong named driver...

Thank you!
I wish you a nice evening.
Regards.
Christopher

### CODE REVIEW

**Comment by CastagnaIT** [comment]
the first commit is not necessary, regulators are the same,
to be precise, the only change to do is change this line:
{ .supply = "smps4", .min_uV = 2200000, .max_uV = 2200000 }, 
 with:
{ .supply = "s4", .min_uV = 2200000, .max_uV = 2200000 },

**Comment by Christopher83** [comment]
Yes, I know that there are no differences, even if that is the old 2.6 code, the new one is not used on cm-10.1_3.0, jb-3.0 and probably on ics-3.0 branches. It is for uniformity...

**Comment by CastagnaIT** [comment]
there is no reason to reuse old methods... sooner or later will be deprecated

**Comment by arco** [comment]
The usage of vreg was deprecated in 3.0 (or maybe already in 2.6.38), and replaced with regulators, so this patch actually reverts to the old way of doing it. The code that's already there without this patch is afaik correct, so unless this fixes something, it should probably stay as it is. It's also afaik related to the tvenc/tvout  stuff, which I think doesn't work in CM, so my suggestion would be to disable it altogether in the board file.

**Comment by Christopher83** [comment]
Sorry for the late reply and misunderstanding...
Ok, now all is clear, thank you very much Stefano and Arne for your explanations.
I close this pull request right now...

**Pull request closed without merging**
