### PR TITLE
ancora_tmo: fix for building wifi modules

### PR DESCRIPTION
**Pull request by jfbs**
Despite being defined in bcmwifi_channels.h, WL_CHANSPEC_CTL_SB_NONE is stating undeclared during a build as such: 

/drivers/net/wireless/bcmdhd/src/wl/sys/wl_roam.c: In function 'get_roam_channel_list':
/drivers/net/wireless/bcmdhd/src/wl/sys/wl_roam.c:91:57: error: 'WL_CHANSPEC_CTL_SB_NONE' undeclared (first use in this function)
make[6]: **\* [drivers/net/wireless/bcmdhd/src/wl/sys/wl_roam.o] Error 1

Declaring it again in wlioctl.h builds working wifi module, but with the warning:

/drivers/net/wireless/bcmdhd/src/wl/sys/wl_cfg80211.c:141:0: warning: "WL_CHANSPEC_CTL_SB_NONE" redefined [enabled by default]
/drivers/net/wireless/bcmdhd/src/include/wlioctl.h:47:0: note: this is the location of the previous definition

### CODE REVIEW

**Comment by doadin** [comment]
Is compiling not working at all for you? I am able to compile kernel fine without it stoping for ancora_tmo.

**Comment by jfbs** [comment]
Compiles and runs well.

**Comment by arco** [comment]
Compiles fine for me without this patch, so I'm not sure why it fails for you.

**Comment by jfbs** [comment]
The 'remove stray include files' commit works perfectly. Prior builds weren't copying modules into obj/KERNEL_OBJ/... Thanks for your help.

**Pull request closed without merging**
