### PR TITLE
Patchset 3

### PR DESCRIPTION
**Pull request by sirmordred**

### CODE REVIEW

**Comment by sirmordred** [comment]
@arco  Any review sir?

thanx
regards

**Comment by arco** [comment]
Haven't had time yet, but a couple of feedbacks though:

Changing the PMEM define seems a bit overkill, and won't really change anything. That it's checked for in the kgsl driver, doesn't mean it's actually using it. ION takes precedence before PMEM. Even my s4mini, which is fully ION, has PMEM defined in defconfig. So has a lot of other devices as well.

Using the wifi driver as built-in instead of module, I'm quite hesitant of doing, unless it has been tested properly to work 100%. I've tried it before, and it didn't go well as our MMC bus tended to get really messed up when enabling/disabling wifi.

About the writeback stuff - I thought we had that discussion before? :)

**Comment by sirmordred** [comment]
seems PMEM codes affected all of the kernel tree and probably CAF forgot to remove some of them(like in kgsl driver which should be fully ION)
and this patch will block out all pmem codes on kernel
and ı didnt see CONFIG_ANDROID_PMEM define in defconfigs of modern devices kernels(like nexus or other fully ION devices)
ı think we can use it but thats your decision(cherry-pick or not)

about built-in wifi driver yeah ı agree to you we must be ensure before doing that
ı will test it and report back to you ASAP

but firstly we must get rid of nvram_net.txt bloat (probably this is used by dhd module)

and about the writeback stuff yeah we discussed that in the past

but why ı submitted the same change again?

because ı hate this line https://github.com/arco/samsung-kernel-msm7x30/blob/cm-11.0/arch/arm/mach-msm/board-ancora.c#L7411 and this workaround too https://github.com/AriesVE-DevCon-TEAM/samsung-kernel-msm7x30/commit/de93550437aff413c795ceaea981b9f3b7369bc8
we have ION memory hole/leak/(whatever you say) and this issue can cause lots of problems in the future ı think(because its part of main functions like memory allocating)
we must find correct solution ı think

**Comment by sirmordred** [comment]
ı don't see any harm of being merged the following 3 commits:
1- https://github.com/sirmordred/samsung-kernel-msm7x30/commit/070cffa3cff94908d6a7aa0f6a181bde02799ff6
2- https://github.com/sirmordred/samsung-kernel-msm7x30/commit/4cb2fe97c42b65ccd8e63b02b7b757bdf0dd93ea
3- https://github.com/sirmordred/samsung-kernel-msm7x30/commit/73e70d777baec0e6d2b70a0af8b9aac166b37adc

the rest of can be abandoned

@arco what do you think master?

**Comment by arco** [comment]
I'm going away this weekend, so will look at it after.

**Comment by sirmordred** [comment]
Ok sir ı will be waiting for your review

**Comment by sirmordred** [comment]
ok ı looked more into main parts of kernel
and there are ifdefed pmem codes on vidc driver and framebuffer driver too

those codes are garbage and maybe can cause some issues

and ı think our kernel must be pmem-less as much as possible :)

ı looked msm7630 defconfig on CAF branch and there is not android_pmem define probably they removed it and ı think we must do the same too

**Pull request closed without merging**
