### PR TITLE
Apache: build A2220

### PR DESCRIPTION
**Pull request by hey-o**

### CODE REVIEW

**Comment by hey-o** [comment]
Sorry, I didn't want to add the last one.

**Comment by hey-o** [comment]
Anyway, is it ok now?
It builds for ariesve, and for apache, it doesn't stop because of it.

**Comment by arco** [comment]
I get these when building for apache:

arch/arm/mach-msm/qdsp5v2/snddev_data_marimba.c:3873:29: error: 'handset_audience_call_rx_data' undeclared here (not in a function)
arch/arm/mach-msm/qdsp5v2/snddev_data_marimba.c:3878:29: error: 'handset_audience_call_tx_data' undeclared here (not in a function)

But it builds ok for the other devices.

**Comment by Motorhead1991** [comment]
I fixed that, check the pull requests.

**Pull request closed without merging**
