### PR TITLE
Various updates to kernel

### PR DESCRIPTION
**Pull request by sirmordred**
hi master ı made some changes
major change: ı returned back to our original ION_CAMERA_HEAP configuration why? because
1th reason:msm7x30 isnt designed to use ION_CP_MM heap so forcing/porting(whatever you say) msm7x30 devices to use ION_CP_MM heap will absolutely reduce the stability on VİDC operations ı think(as we cans see on users post, some users are experiencing random lockup and freezes)

also the following change on media-caf side must be reverted https://github.com/arco/android_hardware_qcom_media-caf/commit/94eac3984755ef1de6a49ed9af22b28da6bbd66b

ı will be waiting for your feedback and review sir

thanx
regards

### CODE REVIEW

**Comment by CastagnaIT** [comment]
we have already discussed this, the change of name of the heap is not a problem, ADCTeam have already done a lot of testing, no problems with our camera lib, and no problems with VIDC or memory management.
if you want more specific information on the operation of memory management ADSP ask to Christopher (ADCTeam).
if you want collaborate, if there is any problems you need to send, dmesg, logcat (or eventually also klastmsg) and specify the sequence of events to recreate the problem. if you rely on rumors does not help us.
if you do not want this you're free to create your own kernel...

**Comment by hurtsky** [comment]
@arco @CastagnaIT @Christopher83  did you noticed @Blefish latest commit? https://github.com/Blefish/android_kernel_huawei_u8800/commit/2145ce9e8f8e4eb288d2ee5f23825df93ca58c8b

he already can get rid off the pmem.. maybe you can take a look more closer to the his repo
https://github.com/Blefish/android_kernel_huawei_u8800/commits/cm-11.0

**Comment by CastagnaIT** [comment]
we do not have the problems of the U8800 blefish had to create the wrapper to suppress their problem on the functioning cma.
as he said this feature is not optimal because the transition is slow

**Comment by hurtsky** [comment]
i see, thank you for the clear explanation.

**Comment by sirmordred** [comment]
you are right CIT ı know ADC did lots of test but generic CAF msm7x30 board, AOSP msm7x30 board and other stock samsung msm7x30 boards dont include ION_CP_MM heap
why ı submitted this change because ı think we must stay inline CAF/AOSP/Samsung as much as possible.
also with this change we dont need to modify media-hal (ı think unnecessary)

**Comment by sirmordred** [comment]
also CastagnaIT can you tell me which libs are created from media-hal(media-caf)??
the following ones?
libmm-omxcore
libOmxCore
libOmxVenc
libOmxVdec
libstagefrighthw
libc2dcolorconvert
libdashplayer

thanx
regards

**Comment by CastagnaIT** [comment]
> you are right CIT ı know ADC did lots of test but generic CAF msm7x30 board, AOSP msm7x30 board and other stock samsung msm7x30 boards dont include ION_CP_MM heap
> why ı submitted this change because ı think we must stay inline CAF/AOSP/Samsung as much as possible.
> also with this change we dont need to modify media-hal (ı think unnecessary)

we have already discussed this also with external developers long ago, the best way to get everyone to agree the dev has been this, not come back on the subject.

The libs created from media-caf are described in all the makefiles, what i remember of your list should be corrected...

**Comment by sirmordred** [comment]
thank you very much CastagnaIT

**Comment by hurtsky** [comment]
@sirmordred where did you get the kernel source for SPH-M840?

**Comment by sirmordred** [comment]
googling .D ım serious :))

**Comment by CastagnaIT** [comment]
LOL....you kidding? samsung has the code opensource free...
http://opensource.samsung.com/

**Comment by sirmordred** [comment]
ahaha :) ı know that CIT but forking it from github repo is easier ı think .D

**Comment by hurtsky** [comment]
If http://opensource.samsung.com i know already.....

**Comment by sirmordred** [comment]
well probably we will never switch back to our original configuration then ım closing it now

**Pull request closed without merging**
