### PR TITLE
Fixed bluetooth poweroff and file transfer sending

### PR DESCRIPTION
**Pull request by CastagnaIT**
"#define BT_BLUEDROID_SUPPORT 1"

why to work on cm10 you must set this to 0?
and on cm10.1 to 1?

### CODE REVIEW

**Comment by arco** [comment]
Because CM10 uses Bluez, and CM10.1 uses Bluedroid. Google switched to Bluedroid in 4.2. They use different methods for sleeping, so the kernel driver had to be patched for CM10.1 for deep sleep to work.

And oh, it doesn't crash anymore sending/receiving files with this patch? Nice! :)

**Comment by CastagnaIT** [comment]
yes i tried several times and it always worked,
try it you too for safety

**Comment by ghost** [comment]
Castagna I compile a kernel from your branch but the bluetooth doesn't work

**Comment by arco** [comment]
Seems to not work here. It still fails during transfer.

**Comment by Keff** [comment]
Yeah, suddenly stop halfway during transfer. But at least won't force reboot :)

**Comment by ghost** [comment]
In ariesve I can't active the bluetooth

**Comment by Keff** [comment]
@Davidteri  hmm perhaps some minor mistake u made, but this work perfectly for casT which holding the same device with you right.

**Comment by ghost** [comment]
OK guys sorry I m lost but this changes are for kernel 3.0 or 3.4????

Thanks for all

**Comment by arco** [comment]
3.4, but I don't see any reason why it wouldn't apply to 3.0 as well.

**Comment by ghost** [comment]
OK Arne thanks

**Comment by CastagnaIT** [comment]
@Davidteri you have to compile from the branch "10.1-cm-btfixed"
and change the define BT_BLUEDROID_SUPPORT to value 0 if you use with CM10.
Cm10.1 of xistance bluetooth does not work, i think something has changed in the rom

@arco the change to the file "hci_ibs.c" is not necessary,
I do not understand why but bluetooth works with CM10 ..
currently i can not test on CM10.1

**Comment by ghost** [comment]
@CastagnaIT  ok thanks I m using my cm10.1 and is for that the bluetooth does not work thanks for all

**Pull request closed without merging**
