### PR TITLE
Fix Whitescreen

### PR DESCRIPTION
**Pull request by doadin**
In my testing this seems to at least partial fix the whitescreen, with the revert to mdp4_overlay_lcdc for battery drain.

It doesnt 100% solve it but the white screen is now a partial image of what should be displayed and it only occures after turning the screen on/off rapidly in a small amount of time. Other then that it seems to work every time i power on. As far as battery goes im not sure if this had any affect.

Looking at the new code there seems to be a commented delay, maybe that might change it the rest of the way? Or where it says set display init after 2 sec maybe increase it to 3?

These where taken from old/newer kernel drop from samsung from ancora_tmo

Edit: I was testing as i was makeing this and it doesnt seem to be related to rapid on/off, it does maybe seem better? And it isnt a full white screen its a partial image like stated above.(improvement?)

### CODE REVIEW

**Comment by arco** [comment]
Thanks, will check it out. Removal of "if((board_lcd_hw_revision==3)" might mess up things with rev. 2 displays though.

**Comment by doadin** [comment]
Yea it might need changes for differnet displays and for ancora defines not just ancora_tmo but it seems like its more reliable? Not sure how often the white screen happens(been a while since i used a build like that) but it hasnt happened once all day today for me with minimal use.

**Comment by doadin** [comment]
If this is infact better might be worth looking into the update lcdc driver CastagnaIT made a while back to fix it. Since its just like the driver used for arasive and others which dont have this glitch?

**Comment by dekadev** [comment]
I've tried to change it. and I think there is no problem white screen lcd in rev 3.

**Comment by doadin** [comment]
Well it defiantly still happens, it just happened for me for the first time today. But i think it is better. Got a few poeple testing/compairing. Im actually still not 100% sure what change made it work better but still unsure if its even better.

**Comment by doadin** [comment]
I do still think that it might happen more often when turning on/off rapidly, which maybe its not able to fully init before the screen actually turns on? I know theres something about wait for vsync in mdp4_overlay_lcdc but im not sure how that relates.

**Comment by dekadev** [comment]
I have added you to lcd rev3 patch, and the problem is almost 80% white screen does not happen again. and I also tried two samsung galaxy wonder that both use rev3, but they are different. for samsung galaxy wonder who the white screen every so often occurs, and the other one does not often happen

**Comment by Keff** [comment]
great thanks, more easier fix for that.. 

I tried revert this commit https://github.com/doadin/samsung-kernel-msm7x30/commit/48fd15f4cd1ac04ca98a5544bb0548692e5232d4, 

but remain

static void s6d16a0x_esd(struct work_struct *work) and
static DECLARE_WORK(lcd_esd_work, s6d16a0x_esd);

will result in less chances of getting white screen too..

**Comment by doadin** [comment]
Second needs testing and might not even help. What im seeing is that sometimes when it starts its more of a gray screen and is acutally usable. So i think maybe it need more time to like render the picture before starting. If this is the case maybe could if the samsung_spi_init there and then instead of trying to find a good delay amount.(might also be faster?)

**Comment by arco** [comment]
Doesn't really fix it, unfortunately. Problem happened after the vsync changes was introduced, so something in there is causing it.

**Comment by LeroViten** [comment]
Currently running 3.4.62 kernel on my Ancora with the 3rd rev of a display panel ...
I can prove that the delay in waking the device is reduced to zero. So there is actually a single rapid flickering without the delay! Great...

**Pull request closed without merging**
